[build]
  command = "npm run build"
  functions = "functions" 
  publish = "dist"

# note: each of these fields are OPTIONAL
[dev]

  framework="#custom"
  command = "npm run dev:webpack"
  targetPort = 8079 
  port = 8080 
  publish = "dist" 
  autoLaunch = false